import Document from '../pages/_document'
import './globals.css'
import './styles.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import 'material-icons/iconfont/material-icons.css';

const poppins = Poppins({
  weight: ['400', '700', "800", "900", "600", "500", "400", "100", "200", "300"],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Movie Verse',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>)
}
